/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author Johan León
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setTitle("Casino Llanogrande");
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = (int) tk.getScreenSize().getWidth();
        int ySize = (int) tk.getScreenSize().getHeight();
        this.setSize(xSize, ySize);
        Inicio();
        Casino();
        setIconImage(new ImageIcon(getClass().getResource("/img/maquina2.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        PRanura1 = new javax.swing.JPanel();
        Ranura11 = new javax.swing.JLabel();
        Ranura13 = new javax.swing.JLabel();
        num1 = new javax.swing.JPanel();
        Ranura12 = new javax.swing.JLabel();
        PRanura2 = new javax.swing.JPanel();
        Ranura21 = new javax.swing.JLabel();
        Ranura23 = new javax.swing.JLabel();
        num2 = new javax.swing.JPanel();
        Ranura22 = new javax.swing.JLabel();
        PRanura3 = new javax.swing.JPanel();
        Ranura33 = new javax.swing.JLabel();
        Ranura31 = new javax.swing.JLabel();
        num3 = new javax.swing.JPanel();
        Ranura32 = new javax.swing.JLabel();
        PRanura4 = new javax.swing.JPanel();
        Ranura43 = new javax.swing.JLabel();
        Ranura41 = new javax.swing.JLabel();
        num4 = new javax.swing.JPanel();
        Ranura42 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        Empezar = new javax.swing.JButton();
        Titulo = new javax.swing.JPanel();
        letra1 = new javax.swing.JLabel();
        letra2 = new javax.swing.JLabel();
        letra3 = new javax.swing.JLabel();
        letra4 = new javax.swing.JLabel();
        letra5 = new javax.swing.JLabel();
        letra6 = new javax.swing.JLabel();
        letra7 = new javax.swing.JLabel();
        letra8 = new javax.swing.JLabel();
        letra9 = new javax.swing.JLabel();
        letra10 = new javax.swing.JLabel();
        letra11 = new javax.swing.JLabel();
        letra12 = new javax.swing.JLabel();
        letra13 = new javax.swing.JLabel();
        letra14 = new javax.swing.JLabel();
        letra15 = new javax.swing.JLabel();
        letra16 = new javax.swing.JLabel();
        letra17 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1310, 760));

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRanura1.setBackground(new java.awt.Color(204, 204, 204));
        PRanura1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranura11.setFont(new java.awt.Font("Casino Queen", 0, 138)); // NOI18N
        Ranura11.setForeground(new java.awt.Color(0, 0, 0));
        Ranura11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Ranura11.setAlignmentY(0.0F);
        Ranura11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura1.add(Ranura11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 130));

        Ranura13.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura13.setForeground(new java.awt.Color(0, 0, 0));
        Ranura13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura1.add(Ranura13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 150));

        num1.setBackground(new java.awt.Color(204, 204, 204));

        Ranura12.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura12.setForeground(new java.awt.Color(0, 0, 0));
        Ranura12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout num1Layout = new javax.swing.GroupLayout(num1);
        num1.setLayout(num1Layout);
        num1Layout.setHorizontalGroup(
            num1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(num1Layout.createSequentialGroup()
                .addComponent(Ranura12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        num1Layout.setVerticalGroup(
            num1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(num1Layout.createSequentialGroup()
                .addComponent(Ranura12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PRanura1.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 140));

        panel.add(PRanura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 190, 400));

        PRanura2.setBackground(new java.awt.Color(204, 204, 204));
        PRanura2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranura21.setFont(new java.awt.Font("Casino Queen", 0, 138)); // NOI18N
        Ranura21.setForeground(new java.awt.Color(0, 0, 0));
        Ranura21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Ranura21.setAlignmentY(0.0F);
        Ranura21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura2.add(Ranura21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        Ranura23.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura23.setForeground(new java.awt.Color(0, 0, 0));
        Ranura23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura2.add(Ranura23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 150));

        num2.setBackground(new java.awt.Color(204, 204, 204));

        Ranura22.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura22.setForeground(new java.awt.Color(0, 0, 0));
        Ranura22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout num2Layout = new javax.swing.GroupLayout(num2);
        num2.setLayout(num2Layout);
        num2Layout.setHorizontalGroup(
            num2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(num2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        num2Layout.setVerticalGroup(
            num2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(num2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PRanura2.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 140));

        panel.add(PRanura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 200, 400));

        PRanura3.setBackground(new java.awt.Color(204, 204, 204));
        PRanura3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranura33.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura33.setForeground(new java.awt.Color(0, 0, 0));
        Ranura33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura3.add(Ranura33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 150));

        Ranura31.setFont(new java.awt.Font("Casino Queen", 0, 138)); // NOI18N
        Ranura31.setForeground(new java.awt.Color(0, 0, 0));
        Ranura31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Ranura31.setAlignmentY(0.0F);
        Ranura31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura3.add(Ranura31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        num3.setBackground(new java.awt.Color(204, 204, 204));

        Ranura32.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura32.setForeground(new java.awt.Color(0, 0, 0));
        Ranura32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout num3Layout = new javax.swing.GroupLayout(num3);
        num3.setLayout(num3Layout);
        num3Layout.setHorizontalGroup(
            num3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(num3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura32, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        num3Layout.setVerticalGroup(
            num3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(num3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PRanura3.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 140));

        panel.add(PRanura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 200, 400));

        PRanura4.setBackground(new java.awt.Color(204, 204, 204));
        PRanura4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ranura43.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura43.setForeground(new java.awt.Color(0, 0, 0));
        Ranura43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura4.add(Ranura43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 150));

        Ranura41.setFont(new java.awt.Font("Casino Queen", 0, 138)); // NOI18N
        Ranura41.setForeground(new java.awt.Color(0, 0, 0));
        Ranura41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ranura41.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Ranura41.setAlignmentY(0.0F);
        Ranura41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PRanura4.add(Ranura41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 130));

        num4.setBackground(new java.awt.Color(204, 204, 204));

        Ranura42.setFont(new java.awt.Font("Casino Queen", 0, 140)); // NOI18N
        Ranura42.setForeground(new java.awt.Color(0, 0, 0));
        Ranura42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout num4Layout = new javax.swing.GroupLayout(num4);
        num4.setLayout(num4Layout);
        num4Layout.setHorizontalGroup(
            num4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(num4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura42, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        num4Layout.setVerticalGroup(
            num4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(num4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(num4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranura42, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        PRanura4.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 140));

        panel.add(PRanura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 190, 400));

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        panel.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        Empezar.setText("Empezar");
        Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarActionPerformed(evt);
            }
        });
        panel.add(Empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, -1, -1));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra1.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra1.setForeground(new java.awt.Color(0, 255, 0));
        letra1.setText("e");
        Titulo.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 60));

        letra2.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra2.setForeground(new java.awt.Color(0, 255, 0));
        letra2.setText("C");
        Titulo.add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 60));

        letra3.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra3.setForeground(new java.awt.Color(0, 255, 0));
        letra3.setText("a");
        Titulo.add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 50, 60));

        letra4.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra4.setForeground(new java.awt.Color(0, 255, 0));
        letra4.setText("s");
        Titulo.add(letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 50, 60));

        letra5.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra5.setForeground(new java.awt.Color(0, 255, 0));
        letra5.setText("i");
        Titulo.add(letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 60));

        letra6.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra6.setForeground(new java.awt.Color(0, 255, 0));
        letra6.setText("n");
        Titulo.add(letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 50, 60));

        letra7.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra7.setForeground(new java.awt.Color(0, 255, 0));
        letra7.setText("o");
        Titulo.add(letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 60));

        letra8.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra8.setForeground(new java.awt.Color(0, 255, 0));
        letra8.setText("l");
        Titulo.add(letra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 60));

        letra9.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra9.setForeground(new java.awt.Color(0, 255, 0));
        letra9.setText("l");
        Titulo.add(letra9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 60));

        letra10.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra10.setForeground(new java.awt.Color(0, 255, 0));
        letra10.setText("a");
        Titulo.add(letra10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 50, 60));

        letra11.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra11.setForeground(new java.awt.Color(0, 255, 0));
        letra11.setText("n");
        Titulo.add(letra11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 50, 60));

        letra12.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra12.setForeground(new java.awt.Color(0, 255, 0));
        letra12.setText("o");
        Titulo.add(letra12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 60, 60));

        letra13.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra13.setForeground(new java.awt.Color(0, 255, 0));
        letra13.setText("g");
        Titulo.add(letra13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 60, 60));

        letra14.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra14.setForeground(new java.awt.Color(0, 255, 0));
        letra14.setText("r");
        Titulo.add(letra14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 50, 60));

        letra15.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra15.setForeground(new java.awt.Color(0, 255, 0));
        letra15.setText("a");
        Titulo.add(letra15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, 60));

        letra16.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra16.setForeground(new java.awt.Color(0, 255, 0));
        letra16.setText("n");
        Titulo.add(letra16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 50, 60));

        letra17.setFont(new java.awt.Font("Budmo Jiggler", 0, 72)); // NOI18N
        letra17.setForeground(new java.awt.Color(0, 255, 0));
        letra17.setText("d");
        Titulo.add(letra17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 50, 60));

        panel.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 0, 910, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Marco.png"))); // NOI18N
        panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_volverActionPerformed

    private void EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarActionPerformed
        Digitos d = new Digitos();
        volver.setEnabled(false);
        Empezar.setEnabled(false);

        d.digitos();
        num1.setBackground(new java.awt.Color(204, 204, 204));
        num2.setBackground(new java.awt.Color(204, 204, 204));
        num3.setBackground(new java.awt.Color(204, 204, 204));
        num4.setBackground(new java.awt.Color(204, 204, 204));
        Ranura12.setForeground(Color.black);
        Ranura22.setForeground(Color.black);
        Ranura32.setForeground(Color.black);
        Ranura42.setForeground(Color.black);

        if (cabeza != null) {

            String ganador = String.valueOf(Ganador());
            new Thread(new Runnable() {
                @Override
                public void run() {

                    int pausa = 0;

                    int ayuda = 0;

                    try {
                        NodoCir aux = d.getCabeza();
                        pausa = 5;
                        while (ayuda != 10) {
                            Ranura11.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura12.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura13.setBorder(BorderFactory.createLineBorder(Color.black));
                            for (int i = 0; i < 10; i++) {
                                if (ayuda < 9) {

                                    Ranura11.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura12.setText(Integer.toString(aux.getValor()));
                                    Ranura13.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (1);

                                } else if (aux.getValor() >= (ganador.charAt(0) - 48)) {
                                    if (ganador.charAt(0) == 48) {
                                        Ranura11.setText("9");
                                        Ranura12.setText("0");
                                        Ranura13.setText("1");

                                    } else {
                                        Ranura11.setText(Integer.toString(aux.getAnt().getValor()));
                                        Ranura12.setText(Integer.toString(aux.getValor()));
                                        Ranura13.setText(Integer.toString(aux.getSgte().getValor()));

                                    }
                                    Ranura12.setForeground(new java.awt.Color(255, 0, 0));
                                    num1.setBorder(BorderFactory.createLineBorder(Color.black));
                                    i = 10;

                                } else {
                                    Ranura11.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura12.setText(Integer.toString(aux.getValor()));
                                    Ranura13.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (1);

                                }

                                aux = aux.getSgte();
                            }
                            ayuda++;
                        }

                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }

                }

            }).start();

            new Thread(new Runnable() {
                @Override
                public void run() {

                    int pausa = 0;

                    int ayuda = 0;

                    try {
                        NodoCir aux = d.getCabeza().getSgte();
                        pausa = 5;
                        while (ayuda != 12) {
                            Ranura21.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura22.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura23.setBorder(BorderFactory.createLineBorder(Color.black));

                            for (int i = 0; i < 10; i++) {
                                if (ayuda < 11) {

                                    Ranura21.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura22.setText(Integer.toString(aux.getValor()));
                                    Ranura23.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (1);

                                } else if (aux.getValor() >= (ganador.charAt(1) - 48)) {

                                    if (ganador.charAt(1) == 48) {
                                        Ranura21.setText("9");
                                        Ranura22.setText("0");
                                        Ranura23.setText("1");

                                    } else {
                                        Ranura21.setText(Integer.toString(aux.getAnt().getValor()));
                                        Ranura22.setText(Integer.toString(aux.getValor()));
                                        Ranura23.setText(Integer.toString(aux.getSgte().getValor()));

                                    }
                                    Ranura22.setForeground(new java.awt.Color(255, 0, 0));
                                    num2.setBorder(BorderFactory.createLineBorder(Color.black));
                                    i = 10;

                                } else {
                                    Ranura21.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura22.setText(Integer.toString(aux.getValor()));
                                    Ranura23.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (2);

                                }

                                aux = aux.getSgte();
                            }
                            ayuda++;
                        }

                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }

                }

            }).start();

            new Thread(new Runnable() {
                @Override
                public void run() {

                    int pausa = 0;

                    int ayuda = 0;

                    try {
                        NodoCir aux = d.getCabeza();
                        pausa = 5;
                        while (ayuda != 14) {
                            Ranura31.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura32.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura33.setBorder(BorderFactory.createLineBorder(Color.black));
                            for (int i = 0; i < 10; i++) {
                                if (ayuda < 13) {

                                    Ranura31.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura32.setText(Integer.toString(aux.getValor()));
                                    Ranura33.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (1);

                                } else if (aux.getValor() >= (ganador.charAt(2) - 48)) {

                                    if (ganador.charAt(2) == 48) {

                                        Ranura31.setText("9");
                                        Ranura32.setText("0");
                                        Ranura33.setText("1");

                                    } else {
                                        Ranura31.setText(Integer.toString(aux.getAnt().getValor()));
                                        Ranura32.setText(Integer.toString(aux.getValor()));
                                        Ranura33.setText(Integer.toString(aux.getSgte().getValor()));

                                    }

                                    Ranura32.setForeground(new java.awt.Color(255, 0, 0));
                                    num3.setBorder(BorderFactory.createLineBorder(Color.black));
                                    i = 10;

                                } else {
                                    Ranura31.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura32.setText(Integer.toString(aux.getValor()));
                                    Ranura33.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (1 / 2);

                                }

                                aux = aux.getSgte();
                            }
                            ayuda++;
                        }

                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }

                }

            }).start();
            new Thread(new Runnable() {
                @Override
                public void run() {

                    int pausa = 0;

                    int ayuda = 0;

                    try {
                        NodoCir aux = d.getCabeza().getSgte();
                        pausa = 5;
                        while (ayuda != 16) {
                            Ranura41.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura42.setBorder(BorderFactory.createLineBorder(Color.black));
                            Ranura43.setBorder(BorderFactory.createLineBorder(Color.black));
                            for (int i = 0; i < 10; i++) {
                                if (ayuda < 15) {

                                    Ranura41.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura42.setText(Integer.toString(aux.getValor()));
                                    Ranura43.setText(Integer.toString(aux.getSgte().getValor()));

                                    Thread.sleep(pausa);
                                    pausa = pausa + (1);

                                } else if (aux.getValor() >= (ganador.charAt(3) - 48)) {

                                    if (ganador.charAt(3) == 48) {

                                        Ranura41.setText("9");
                                        Ranura42.setText("0");
                                        Ranura43.setText("1");

                                    } else {
                                        Ranura41.setText(Integer.toString(aux.getAnt().getValor()));
                                        Ranura42.setText(Integer.toString(aux.getValor()));
                                        Ranura43.setText(Integer.toString(aux.getSgte().getValor()));

                                    }
                                    Ranura42.setForeground(new java.awt.Color(255, 0, 0));
                                    num4.setBorder(BorderFactory.createLineBorder(Color.black));
                                    Empezar.setEnabled(true);
                                    volver.setEnabled(true);
                                    i = 10;

                                } else {
                                    Ranura41.setText(Integer.toString(aux.getAnt().getValor()));
                                    Ranura42.setText(Integer.toString(aux.getValor()));
                                    Ranura43.setText(Integer.toString(aux.getSgte().getValor()));
                                    Thread.sleep(pausa);
                                    pausa = pausa + (7 / 10);

                                }

                                aux = aux.getSgte();
                            }
                            ayuda++;
                        }

                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }

                }

            }).start();

            new Thread(new Runnable() {
                @Override
                public void run() {

                    try {
                      
                      
                            FileInputStream fis;
                            Player player;
                            File sonido= new File("src\\musica\\maquina.mp3");
                            fis = new FileInputStream(sonido.getAbsolutePath());
                            BufferedInputStream bis = new BufferedInputStream(fis);
                            player = new Player(bis);
                            player.play();
                        

                    } catch (Exception ex) {
                        System.out.println(ex);
                    }

                }

            }).start();

        } else {
            volver.setEnabled(true);
            Empezar.setEnabled(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "No se han ingresado maquinas para la rifa");

        }

    }//GEN-LAST:event_EmpezarActionPerformed

    private Nodo cabeza;
    private Nodo cola;
    private int tam;

    public void ListaEnlazada() {
        cabeza = null;  //puntero a tierra
        tam = 0;
    }

    public Nodo getCola() {
        return cola;
    }

    public void setCola(Nodo cola) {
        this.cola = cola;
    }

    public Nodo getCabeza() {
        return cabeza;
    }

    public void setCabeza(Nodo cabeza) {
        this.cabeza = cabeza;
    }

    public boolean esVacia() {
        return cabeza == null;  // if(cabeza == null)
    }

    public int getTam() {
        return tam;
    }

    public void setTam(int tam) {
        this.tam = tam;
    }

    public void MostrarLista() {
        int pos = 1;
        Nodo aux = cabeza;
        boolean flag = true;
        int contador = 0;
        if (!esVacia()) {
            while (flag == true) {
                if (contador == this.getTam()) {
                    flag = false;
                } else {
                    System.out.print(pos + "[" + aux.getValor() + "]" + "->");
                    pos++;
                    aux = aux.getSgte();
                    contador++;
                }

            }
        } else {
            System.out.println("LA LISTA ESTA VACIA");
        }
    }

    public String Ganador() {

        Nodo aux = cabeza;
        boolean flag = true;
        int contador = 1;
        int r = random();
        while (flag == true) {
            if (contador == r) {
                flag = false;

            } else {
                aux = aux.getSgte();
                contador++;

            }

        }

        return aux.getValor();

    }

    public void agregarAlFinal(String valor) {
        Nodo nuevo = new Nodo();
        nuevo.setValor(valor);

        if (esVacia()) {
            cabeza = nuevo;

        } else {

            Nodo aux = cabeza;
            while (aux.getSgte() != null) {

                aux = aux.getSgte();

            }

            aux.setSgte(nuevo);

        }

        tam++;

    }

    public void elimRef(String ref) {

        Nodo aux = cabeza;
        Nodo aux2 = null;
        if (Buscar(ref)) {
            if (this.getTam() == 1) {
                cabeza = null;
                aux.setSgte(null);

            } else if (cabeza.getValor().equals(ref)) {
                aux2 = aux;
                cabeza = aux.getSgte();
                aux2.setSgte(null);
            } else {
                while (!aux.getValor().equals(ref)) {
                    aux2 = aux;
                    aux = aux.getSgte();
                }

                aux2.setSgte(aux.getSgte());
                aux.setSgte(null);
            }
            tam--;
        }

    }

    public boolean Buscar(String ref) {
        Nodo aux = cabeza;
        boolean flag = false;
        if (!esVacia()) {

            if (ref.equals(cabeza.getValor())) {
                flag = true;
            } else {

                while (aux != cola) {

                    if (ref.equals(aux.getValor())) {

                        flag = true;

                    } else {

                    }
                    aux = aux.getSgte();
                }
            }
        }

        return flag;
    }

    public int random() {
        int M = this.getTam();
        Random rn = new Random();
        int r = rn.nextInt(M) + 1; // Valor entre 1 y M, ambos incluidos. donde M = tamaño de la lista 

        return r;

    }

    public void Inicio() {
        Random r = new Random();
        int inicio1 = r.nextInt(7) + 1;
        int inicio2 = r.nextInt(7) + 1;
        int inicio3 = r.nextInt(7) + 1;
        int inicio4 = r.nextInt(7) + 1;

        Ranura11.setText(String.valueOf(inicio1 - 1));
        Ranura12.setText(String.valueOf(inicio1));
        Ranura13.setText(String.valueOf(inicio1 + 1));

        Ranura21.setText(String.valueOf(inicio2 - 1));
        Ranura22.setText(String.valueOf(inicio2));
        Ranura23.setText(String.valueOf(inicio2 + 1));

        Ranura31.setText(String.valueOf(inicio3 - 1));
        Ranura32.setText(String.valueOf(inicio3));
        Ranura33.setText(String.valueOf(inicio3 + 1));

        Ranura41.setText(String.valueOf(inicio4 - 1));
        Ranura42.setText(String.valueOf(inicio4));
        Ranura43.setText(String.valueOf(inicio4 + 1));

        Ranura11.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura12.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura13.setBorder(BorderFactory.createLineBorder(Color.black));

        Ranura21.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura22.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura23.setBorder(BorderFactory.createLineBorder(Color.black));

        Ranura31.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura32.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura33.setBorder(BorderFactory.createLineBorder(Color.black));

        Ranura41.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura42.setBorder(BorderFactory.createLineBorder(Color.black));
        Ranura43.setBorder(BorderFactory.createLineBorder(Color.black));

    }

    public void Casino() {
        new Thread(new Runnable() {
            @Override
            public void run() {

                while (true) {
                    try {
                        for (int i = 0; i <= 255; i++) {
                            if (i < 192) {
                                letra1.setForeground(new java.awt.Color(i, i, i));
                                letra2.setForeground(new java.awt.Color(i, i, i));
                                letra3.setForeground(new java.awt.Color(i, i, i));
                                letra4.setForeground(new java.awt.Color(i, i, i));
                                letra5.setForeground(new java.awt.Color(i, i, i));
                                letra6.setForeground(new java.awt.Color(i, i, i));
                                letra7.setForeground(new java.awt.Color(i, i, i));
                                letra8.setForeground(new java.awt.Color(i, i, i));
                                letra9.setForeground(new java.awt.Color(i, i, i));
                                letra10.setForeground(new java.awt.Color(i, i, i));
                                letra11.setForeground(new java.awt.Color(i, i, i));
                                letra12.setForeground(new java.awt.Color(i, i, i));
                                letra13.setForeground(new java.awt.Color(i, i, i));
                                letra14.setForeground(new java.awt.Color(i, i, i));
                                letra15.setForeground(new java.awt.Color(i, i, i));
                                letra16.setForeground(new java.awt.Color(i, i, i));
                                letra17.setForeground(new java.awt.Color(i, i, i));
                            } else {
                                letra1.setForeground(new java.awt.Color(192, 192, 192));
                                letra2.setForeground(new java.awt.Color(192, 192, 192));
                                letra3.setForeground(new java.awt.Color(192, 192, 192));
                                letra4.setForeground(new java.awt.Color(192, 192, 192));
                                letra5.setForeground(new java.awt.Color(192, 192, 192));
                                letra6.setForeground(new java.awt.Color(192, 192, 192));
                                letra7.setForeground(new java.awt.Color(192, 192, 192));
                                letra8.setForeground(new java.awt.Color(192, 192, 192));
                                letra9.setForeground(new java.awt.Color(192, 192, 192));
                                letra10.setForeground(new java.awt.Color(192, 192, 192));
                                letra11.setForeground(new java.awt.Color(192, 192, 192));
                                letra12.setForeground(new java.awt.Color(192, 192, 192));
                                letra13.setForeground(new java.awt.Color(192, 192, 192));
                                letra14.setForeground(new java.awt.Color(192, 192, 192));
                                letra15.setForeground(new java.awt.Color(192, 192, 192));
                                letra16.setForeground(new java.awt.Color(192, 192, 192));
                                letra17.setForeground(new java.awt.Color(192, 192, 192));

                            }
                            Thread.sleep(35);
                        }
                        for (int i = 0; i <= 255; i++) {
                            if (i % 2 == 0) {
                                letra2.setForeground(new java.awt.Color(192, 192, 192));
                                letra4.setForeground(new java.awt.Color(192, 192, 192));
                                letra6.setForeground(new java.awt.Color(192, 192, 192));
                                letra8.setForeground(new java.awt.Color(192, 192, 192));
                                letra10.setForeground(new java.awt.Color(192, 192, 192));
                                letra12.setForeground(new java.awt.Color(192, 192, 192));
                                letra14.setForeground(new java.awt.Color(192, 192, 192));
                                letra16.setForeground(new java.awt.Color(192, 192, 192));
                                letra1.setForeground(new java.awt.Color(192, 192, 192));

                                letra3.setForeground(Color.yellow);
                                letra5.setForeground(Color.yellow);
                                letra7.setForeground(Color.yellow);
                                letra9.setForeground(Color.yellow);
                                letra11.setForeground(Color.yellow);
                                letra13.setForeground(Color.yellow);
                                letra15.setForeground(Color.yellow);
                                letra17.setForeground(Color.yellow);

                            } else {

                                letra3.setForeground(new java.awt.Color(192, 192, 192));
                                letra5.setForeground(new java.awt.Color(192, 192, 192));
                                letra7.setForeground(new java.awt.Color(192, 192, 192));
                                letra9.setForeground(new java.awt.Color(192, 192, 192));
                                letra11.setForeground(new java.awt.Color(192, 192, 192));
                                letra13.setForeground(new java.awt.Color(192, 192, 192));
                                letra15.setForeground(new java.awt.Color(192, 192, 192));

                                letra17.setForeground(new java.awt.Color(192, 192, 192));

                                letra2.setForeground(Color.yellow);
                                letra4.setForeground(Color.yellow);
                                letra6.setForeground(Color.yellow);
                                letra8.setForeground(Color.yellow);
                                letra10.setForeground(Color.yellow);
                                letra12.setForeground(Color.yellow);
                                letra14.setForeground(Color.yellow);
                                letra16.setForeground(Color.yellow);
                                letra16.setForeground(Color.yellow);
                                letra1.setForeground(Color.yellow);
                            }
                            Thread.sleep(120);

                        }
                        int contador2 = 0;
                        while (contador2 != 6) {
                            letra2.setForeground(new java.awt.Color(255, 0, 0));
                            letra3.setForeground(new java.awt.Color(255, 0, 0));
                            letra4.setForeground(new java.awt.Color(255, 0, 0));
                            letra5.setForeground(new java.awt.Color(255, 0, 0));
                            letra6.setForeground(new java.awt.Color(255, 0, 0));
                            letra7.setForeground(new java.awt.Color(255, 0, 0));
                            letra8.setForeground(new java.awt.Color(255, 0, 0));
                            letra9.setForeground(new java.awt.Color(255, 0, 0));
                            letra10.setForeground(new java.awt.Color(255, 0, 0));
                            letra11.setForeground(new java.awt.Color(255, 0, 0));
                            letra12.setForeground(new java.awt.Color(255, 0, 0));
                            letra13.setForeground(new java.awt.Color(255, 0, 0));
                            letra14.setForeground(new java.awt.Color(255, 0, 0));
                            letra15.setForeground(new java.awt.Color(255, 0, 0));
                            letra16.setForeground(new java.awt.Color(255, 0, 0));
                            letra17.setForeground(new java.awt.Color(255, 0, 0));
                            letra1.setForeground(new java.awt.Color(255, 0, 0));
                            int contador = 0;

                            while (contador != 19) {
                                if (contador == 1) {
                                    letra2.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 2) {
                                    letra3.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 3) {
                                    letra4.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 4) {
                                    letra5.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 5) {
                                    letra6.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 6) {
                                    letra7.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 7) {
                                    letra8.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 8) {
                                    letra9.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 9) {
                                    letra10.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 10) {
                                    letra11.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 11) {
                                    letra12.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 12) {
                                    letra13.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 13) {
                                    letra14.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 14) {
                                    letra15.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 15) {
                                    letra16.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 16) {
                                    letra17.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                if (contador == 17) {
                                    letra1.setForeground(new java.awt.Color(0, 255, 0));
                                }
                                Thread.sleep(250);
                                contador++;
                            }
                            contador2++;
                        }

                    } catch (Exception ex) {
                        System.out.println(ex);
                    }

                }
            }
        }).start();
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Empezar;
    private javax.swing.JPanel PRanura1;
    private javax.swing.JPanel PRanura2;
    private javax.swing.JPanel PRanura3;
    private javax.swing.JPanel PRanura4;
    private javax.swing.JLabel Ranura11;
    public javax.swing.JLabel Ranura12;
    private javax.swing.JLabel Ranura13;
    private javax.swing.JLabel Ranura21;
    public javax.swing.JLabel Ranura22;
    private javax.swing.JLabel Ranura23;
    private javax.swing.JLabel Ranura31;
    public javax.swing.JLabel Ranura32;
    private javax.swing.JLabel Ranura33;
    private javax.swing.JLabel Ranura41;
    public javax.swing.JLabel Ranura42;
    private javax.swing.JLabel Ranura43;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel letra1;
    private javax.swing.JLabel letra10;
    private javax.swing.JLabel letra11;
    private javax.swing.JLabel letra12;
    private javax.swing.JLabel letra13;
    private javax.swing.JLabel letra14;
    private javax.swing.JLabel letra15;
    private javax.swing.JLabel letra16;
    private javax.swing.JLabel letra17;
    private javax.swing.JLabel letra2;
    private javax.swing.JLabel letra3;
    private javax.swing.JLabel letra4;
    private javax.swing.JLabel letra5;
    private javax.swing.JLabel letra6;
    private javax.swing.JLabel letra7;
    private javax.swing.JLabel letra8;
    private javax.swing.JLabel letra9;
    private javax.swing.JPanel num1;
    private javax.swing.JPanel num2;
    private javax.swing.JPanel num3;
    private javax.swing.JPanel num4;
    private javax.swing.JPanel panel;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
