/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author Johan León
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setTitle("Menú");
        this.setLocationRelativeTo(null);
        centrarDatos();
        Iniciar();
        setIconImage(new ImageIcon(getClass().getResource("/img/maquina2.png")).getImage());
        btnEliminar.setEnabled(false);
    }
    int rowSel;

    public int getRowSel() {
        return rowSel;
    }

    public void setRowSel(int rowSel) {
        this.rowSel = rowSel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        numMaquina = new javax.swing.JTextField();
        ScrollPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numMaquinaEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        Panel1.setBackground(new java.awt.Color(0, 0, 0));
        Panel1.setForeground(new java.awt.Color(204, 0, 0));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("Número de Maquina");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        Panel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        numMaquina.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        numMaquina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMaquinaActionPerformed(evt);
            }
        });
        numMaquina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numMaquinaKeyTyped(evt);
            }
        });
        Panel1.add(numMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 240, 40));

        tabla.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.getTableHeader().setFont(new Font("sansserif", 0, 36));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maquinas en juego"
            }

        ));
        tabla.setAlignmentX(0.0F);
        tabla.setAlignmentY(0.0F);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setEnabled(false);
        tabla.setRowHeight(36);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        ScrollPane.setViewportView(tabla);

        Panel1.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, 320, 520));

        jTabbedPane1.addTab("Ingresar", Panel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollPane1.setEnabled(false);

        tabla1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        tabla1.setForeground(new java.awt.Color(255, 255, 255));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maquinas en juego"
            }

        ));
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        tabla1.getColumnModel().getColumn(0).setCellRenderer(tcr);
        tabla1.setAlignmentX(0.0F);
        tabla1.setAlignmentY(0.0F);
        tabla1.setCellSelectionEnabled(true);
        tabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla1.setEnabled(false);
        tabla1.setRowHeight(36);
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        ScrollPane1.setViewportView(tabla1);

        jPanel2.add(ScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, 320, 520));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel2.setText("Número de Maquina");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        numMaquinaEliminar.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        numMaquinaEliminar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numMaquinaEliminar.setEnabled(false);
        numMaquinaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMaquinaEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(numMaquinaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 240, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jTabbedPane1.addTab("Eliminar", jPanel2);

        Comenzar.setBackground(new java.awt.Color(204, 0, 0));
        Comenzar.setFont(new java.awt.Font("Casino Queen", 0, 75)); // NOI18N
        Comenzar.setForeground(new java.awt.Color(255, 255, 255));
        Comenzar.setText("Comenzar");
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(Comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(Comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empezar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMaquinaActionPerformed
    int contador = 0;

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed

        if (numMaquina.getText().length() < 4) {
            numMaquina.setText("");
            JOptionPane.showMessageDialog(null, "No Ingresó un Código válido", "Aviso", 2);

        } else if (numMaquina.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No Ingresó Ninguna Máquina", "Aviso", 2);
        } else if (i.Buscar(numMaquina.getText())) {

            numMaquina.setText("");
            JOptionPane.showMessageDialog(null, "El Código que ingresó ya existe", "Aviso", 2);

        } else {

            DefaultTableModel temp = (DefaultTableModel) tabla.getModel();

            Object nuevo[] = {"", ""};
            temp.addRow(nuevo);
            tabla.setValueAt(numMaquina.getText(), contador, 0);

            DefaultTableModel temp1 = (DefaultTableModel) tabla1.getModel();

            Object nuevo1[] = {"", ""};
            temp1.addRow(nuevo1);
            tabla1.setValueAt(numMaquina.getText(), contador, 0);

            i.agregarAlFinal(numMaquina.getText());
            contador++;
            numMaquina.setText("");

        }


    }//GEN-LAST:event_IngresarActionPerformed

    private void numMaquinaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMaquinaEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMaquinaEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (numMaquinaEliminar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se ha ingresadó ninguna máquina", "Aviso", 2);

        } else {
            i.elimRef(numMaquinaEliminar.getText());
            DefaultTableModel temp1 = (DefaultTableModel) tabla1.getModel();
            DefaultTableModel temp = (DefaultTableModel) tabla.getModel();
            temp1.removeRow(this.rowSel);
            temp.removeRow(this.rowSel);
            numMaquinaEliminar.setText("");
            JOptionPane.showMessageDialog(null, "La Máquina se ha Borrado", "Aviso", 1);
            btnEliminar.setEnabled(false);

            contador--;
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void numMaquinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numMaquinaKeyTyped
        int num = 4;
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor solo ingrese números");
            numMaquina.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por favor solo ingrese numeros");
            numMaquina.setCursor(null);
        }
        if (numMaquina.getText().length() >= num) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Por favor introduzca un código válido");
        }

    }//GEN-LAST:event_numMaquinaKeyTyped

    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed

        this.setVisible(true);
        i.setVisible(true);

    }//GEN-LAST:event_ComenzarActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        int fila = this.tabla1.rowAtPoint(evt.getPoint());
        this.rowSel = fila;
        this.numMaquinaEliminar.setText(tabla1.getValueAt(fila, 0).toString());
        this.btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tabla1MouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila = this.tabla.rowAtPoint(evt.getPoint());
       
        this.numMaquina.setText(tabla.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tablaMouseClicked
    public void Iniciar() {

        if (i.getTam() != 0) {
            Nodo aux = i.getCabeza();
            while (aux != null) {
                if (numMaquina.getText().equals("")) {

                    JOptionPane.showMessageDialog(null, "No Ingresó Ninguna Máquina", "Aviso", 2);
                } else {
                    DefaultTableModel temp = (DefaultTableModel) tabla.getModel();

                    Object nuevo[] = {"", ""};
                    temp.addRow(nuevo);
                    tabla.setValueAt(numMaquina.getText(), contador, 0);

                    DefaultTableModel temp1 = (DefaultTableModel) tabla1.getModel();

                    Object nuevo1[] = {"", ""};
                    temp1.addRow(nuevo1);
                    tabla1.setValueAt(numMaquina.getText(), contador, 0);

                    i.agregarAlFinal(numMaquina.getText());

                    contador++;
                    numMaquina.setText("");
                }
                aux = aux.getSgte();
            }
        }
    }

    public void centrarDatos() {

        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
        tabla.getColumnModel().getColumn(0).setCellRenderer(modelocentrar);
    }
    Interfaz i = new Interfaz();

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (Exception ex) {
            System.out.println(ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comenzar;
    private javax.swing.JButton Ingresar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField numMaquina;
    private javax.swing.JTextField numMaquinaEliminar;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
